FROM python:3.9-slim

WORKDIR /app

COPY lib/ /app/lib/
COPY corpuses/ /app/corpuses/
COPY server/ /app/

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x /app/lib/libautocomplete.so

EXPOSE 8000
CMD ["python", "app.py"]